// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oiihdeukymsyzfjkeneu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9paWhkZXVreW1zeXpmamtlbmV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMzk3MTEsImV4cCI6MjA2MzkxNTcxMX0.G9WcqGKJEKjqHr4aPSt7moHgFgim5I_u2cBonHGymPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);